//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackEmployeeAbsence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbsenceList
    {
        public int LeaveId { get; set; }
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime LeaveDate { get; set; }
        public string LeaveReason { get; set; }
    }
}
